title: Freelance Journalists Union · Industrial Workers of the World
email: freelancejournalists@iww.org
baseurl: ""
url: "https://freelancejournalistsunion.org"
description: IWW Freelance Journalists Union

future: true

paypal: freelancejournalists@iww.org

logo: /assets/logo.png

defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/social.png
  -
    scope:
      path: "statements"
      type: "posts"
    values:
      layout: "post"
      permalink: "/:categories/:year/:i_month/:i_day/:slug"

social_icons:
  - twitter_username: IWWFJU
  - instagram_username: freelancejournalistsunion
  - facebook_username: IWWFJU

social:
  name: IWW FJU
  links:
    - https://twitter.com/iwwfju
    - https://instagram.com/freelancejournalistsunion
    - https://facebook.com/iwwfju

twitter:
  username: iwwfju
  card: summary

facebook:
  publisher: iwwfju

cloudflare_web_analytics_token: 16aa4822492b4e61be2a829974c1455c

markdown: kramdown

kramdown:
  parse_span_html: true
  input: GFM

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 5
paginate_path: "/statements/:num/"
