title: Freelance Journalists Union · Industrial Workers of the World
email: organize@wobblycity.org
baseurl: ""
url: "https://freelancejournalistsunion.org"
description: Freelance Journalists Union

future: true

paypal: freelancejournalists@iww.org

twitter_username: IWW_FJU
instagram_username: freelancejournalistsunion
facebook_username: IWWFreelanceJournalistsUnion

social:
  name: IWW FJU
  links:
    - https://www.twitter.com/IWW_FJU
    - https://instagram.com/freelancejournalistsunion
    - https://www.facebook.com/IWWFreelanceJournalistsUnion

twitter:
  username: IWW_FJU
  card: summary

facebook:
  publisher: IWWFreelanceJournalistsUnion

markdown: kramdown

kramdown:
  parse_span_html: true
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

image: /assets/social.png
logo: /assets/logo.png

collections:
  events:
    output: true
    path: ""
    permalink: /events/:path/

paginate: 5
paginate_path: "/news/:num/"
