title: Freelance Journalists Union · Industrial Workers of the World
email: freelancejournalists@iww.org
baseurl: ""
url: "https://freelancejournalistsunion.org"
description: The latest news and happenings from the NYC Industrial Workers of the World! · An injury to one is an injury to all.

future: true

paypal: freelancejournalists@iww.org

twitter_username: IWW_FJU

social:
  name: Freelance Journalists Union
  links:
    - https://www.twitter.com/IWW_FJU

twitter:
  username: IWW_FJU
  card: summary

markdown: kramdown

kramdown:
  parse_span_html: true
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

image: /assets/social.png
logo: /assets/logo.png

paginate: 5
paginate_path: "/news/:num/"
